#version: "3.8"
services:
  frontend:
    image: scaletg/frontend:v1
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    container_name: backend
    image: scale/express	    
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
